version: "3"
services:
  gitlab-runner:
    command: [
      'register',
      '--non-interactive',
      '--docker-image', 'alpine:latest',
      '--executor', 'docker',
      '--url', 'https://gitlab.com/',
      '--registration-token', '$PROJECT_REGISTRATION_TOKEN',
      '--description', 'docker-runner',
      '--tag-list', 'docker,aws',
      '--run-untagged',
      '--locked', 'false',
      '--docker-privileged',
      '--docker-volumes',
      '/var/run/docker.sock:/var/run/docker.sock',
    ]
